In [687]:
import numpy as np

Creating arrays:

1. Create a rank 2 (2D) array.

In [688]:
arr = np.array([[11,12,13,14],[15,16,17,18]])
print(arr)

[[11 12 13 14]
 [15 16 17 18]]


Use the appropriate functions to solve the following questions:

1. Create an array with 4 rows and 3 columns of zeros.

In [689]:
arr = np.zeros((4,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


2. Create an array of ones that has 3 rows and 4 columns.

In [690]:
arr = np.ones((3,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


3. Create an array containing integers 4 to 13 inclusive.

In [691]:
arr = np.arange(4,14)
print(arr)

[ 4  5  6  7  8  9 10 11 12 13]


4. Create an array containing [0., 1.5, 3., 4.5]

In [692]:
arr = np.array([0.,1.5,3.,4.5]) # the '.' explicitly shows it's a floating-point num
print(arr)

[0.  1.5 3.  4.5]


5. Create a 2 by 2 array containing '4' in each position.

In [693]:
arr = np.full((2,2),4)
print(arr)

[[4 4]
 [4 4]]


6. Create an identity matrix of size 4 and a diagonal matrix with [10,12] as the diagonals.

In [694]:
print("Identity:\n", np.identity(4), end = "\n\n")
print("Diagonal:\n", np.diag([10,12]))

Identity:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Diagonal:
 [[10  0]
 [ 0 12]]


7. Create a 3 by 3 array with random floats in [0, 10]

In [695]:
arr = np.random.uniform(0,11,(3,3))
print(arr)

[[9.98121118 8.16660585 8.73091391]
 [9.25576267 7.25182731 3.32057758]
 [7.12694168 7.90587994 8.89735723]]


8. Create a 3 by 3 array with random integers in [10, 20]

In [696]:
arr = np.random.uniform(10,21,(3,3))
print(arr)

[[16.84066805 17.26049032 19.82745883]
 [16.09329062 14.28888502 16.96668283]
 [17.59029506 11.42219969 16.83224505]]


Slicing arrays:

1. Use this array for the following practice:

myArray = np.array([[11,12,13], [14,15,16], [17,18,19]])


a. Get a subarray of the first row and first 2 columns.
b. Change all elements in 1st and second row to 0.

In [697]:
myArray = np.array([[11,12,13], [14,15,16], [17,18,19]])
print("Part A:\n", myArray[0,:2], end="\n\n")

myArray[:2] = 0
print("Part B:\n", myArray)

Part A:
 [11 12]

Part B:
 [[ 0  0  0]
 [ 0  0  0]
 [17 18 19]]


2. Create an array that contains [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20] and reverse the order.

In [698]:
arr = np.arange(21)
reversedArr = np.flip(arr)
print(reversedArr)

[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


Reshaping:

1. Use this array for the following practice: 

myArray = np.array([[11,12,13], [14,15,16]])

Reshape the array to an array with 3 rows.

In [699]:
myArray = np.array([[11,12,13], [14,15,16]])
reshapedArr = myArray.reshape(3,-1) # -1 automatically calculates num of columns needed
print(reshapedArr)

[[11 12]
 [13 14]
 [15 16]]


Math:

Use this array for the following practice: 

In [700]:
myArray = np.arange(10)

1. Find the square of every number in array

In [701]:
sq = np.square(myArray)
print(sq)

[ 0  1  4  9 16 25 36 49 64 81]


2. Find the square root of every number in array

In [702]:
sq_root = np.sqrt(myArray)
print(sq_root)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


3. Multiply the square of each number in array with its respective square root

In [703]:
mul = sq * sq_root
print(mul)

[  0.           1.           5.65685425  15.58845727  32.
  55.90169944  88.18163074 129.64181424 181.01933598 243.        ]


Adding elements:

Use this array for the following practice:

In [704]:
myArray = np.array([[11,12,13], [14,15,16], [17,18,19]])

1. Add a new row of elements containing 20, 21 and 22

In [705]:
newArr = np.concatenate((myArray,np.arange(20,23).reshape(1,3)),axis=0) # you can also use np.vstack to add rows
print(newArr)

[[11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]]


2. Add a new column of elements containing 30, 40 and 50

In [706]:
newArr = np.concatenate((myArray,np.array([[30],[40],[50]])),axis=1)
print(newArr)

[[11 12 13 30]
 [14 15 16 40]
 [17 18 19 50]]


Inserting elements:

In [707]:
myArray = np.zeros((2,2))

1. Add 1 column of 1 to myArray

In [708]:
myArray = np.insert(myArray,2,1,axis=1)
print(myArray)

[[0. 0. 1.]
 [0. 0. 1.]]


2. Add 2 rows of 2 to the answer from part 1

In [709]:
myArray = np.vstack([myArray,np.full((2, myArray.shape[1]),2)])
print(myArray)

[[0. 0. 1.]
 [0. 0. 1.]
 [2. 2. 2.]
 [2. 2. 2.]]


3. Remove the last column

In [710]:
myArray = np.delete(myArray, -1, axis=1) # this uses negative array indexing
print(myArray)

[[0. 0.]
 [0. 0.]
 [2. 2.]
 [2. 2.]]


4. Remove the last row

In [711]:
myArray = np.delete(myArray, -1, axis=0)
print(myArray)

[[0. 0.]
 [0. 0.]
 [2. 2.]]


Remove elements:

1. Remove the elements from the middle column of this array:

In [712]:
myArray = np.array([[1, 2, 3], [4, 5, 6], [9, 8, 7]])
print(myArray)

[[1 2 3]
 [4 5 6]
 [9 8 7]]


In [713]:
myArray = np.delete(myArray, myArray.shape[1]//2, axis=1) # '//' is int division
print(myArray)

[[1 3]
 [4 6]
 [9 7]]


Test exercise:

1. Replace all odd numbers in the given array with -1

In [714]:
exercise_1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(exercise_1)

[0 1 2 3 4 5 6 7 8 9]


In [715]:
exercise_1[exercise_1 % 2 == 1] = -1
print(exercise_1)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


2. Convert a 1-D array into a 2-D array with 3 rows

In [716]:
exercise_2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
print(exercise_2)

[0 1 2 3 4 5 6 7 8]


In [717]:
exercise_2 = exercise_2.reshape(3,-1)
print(exercise_2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Add 202 to all the values in given array

In [718]:
exercise_3 = np.arange(4).reshape(2,-1)
print(exercise_3)

[[0 1]
 [2 3]]


In [719]:
exercise_3 += 202
print(exercise_3)

[[202 203]
 [204 205]]


4. Generate a 1-D array of 10 random integers. Each integer should be a number between 30 and 40 (inclusive)

In [720]:
exercise_4 = np.random.randint(30,41,10)
print(exercise_4)

[37 34 33 31 31 31 32 31 35 37]


5. Find the positions of:

a. elements in x where its value is more than its corresponding element in y, and 
b. elements in x where its value is equals to its corresponding element in y.

In [721]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])

In [722]:
pos_greater = np.where(x > y)
pos_equal = np.where(x == y)
print("Positions Greater:\n", pos_greater, "\n\n", "Positions Equal:\n", pos_equal)

Positions Greater:
 (array([1, 2, 4, 5, 6, 7, 8, 9]),) 

 Positions Equal:
 (array([0]),)


6. Extract the first four columns of this 2-D array

In [723]:
exercise_6 = np.arange(100).reshape(5,-1)
print(exercise_6)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]


In [724]:
exercise_6 = exercise_6[:,:4]
print(exercise_6)

[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]
